# Generated by Django 4.2b1 on 2024-12-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_remove_user_role_user_is_candidate_user_is_recruiter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedjob',
            old_name='created_at',
            new_name='applied_at',
        ),
    ]
